version: 2.1
orbs:
  python: circleci/python@0.2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.9.2

    #working_directory: ~/Assignment3-4

    steps:
     
      - checkout
      - python/install-packages
      - run:
          name: run tests
          command: |
            pipenv run python manage.py test
      
      -store_test_results:
         path: test-results
      
      -store_artifacts:
        path: test-results
        destination: tr1
     
          #name: install dependencies
          #command: |
            #python -m venv venv
            #. venv/bin/activate
            #pip install -r requirements.txt
     
      #- run:
          #name: run tests
          #command: |
            #. venv/bin/activate
            
            #python manage.py test
