version: 2.1
orbs:
  python: circleci/python@0.2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.9.2
      - image: circleci/python:jessie-node-browsers

    #working_directory: ~/Assignment3-4

    steps:
     
      - checkout
      #- python/install-packages
      
      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pipenv run python manage.py test
      - run:
          name: install geckodriver
          command: |
          sudo wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
          sudo tar xf geckodriver-v0.19.1-linux64.tar.gz -C /usr/local/bin
      
      - store_test_results:
         path: test-results
      
      #- store_artifacts:
        #path: test-results
        #destination: tr1
     
          #name: install dependencies
          #command: |
            #python -m venv venv
            #. venv/bin/activate
            #pip install -r requirements.txt
     
      #- run:
          #name: run tests
          #command: |
            #. venv/bin/activate
            
            #python manage.py test
